### ISSUE TITLE
aws deployment instructions appear to be incomplete

### ISSUE THREAD

**Issue by nomicode** [crate/cratedb-guide#22]
###  Documentation feedback

 
- Page title: Run CrateDB on Amazon Web Services (AWS)
- Page URL: https://crate.io/docs/crate/howtos/en/latest/deployment/cloud/aws/index.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/deployment/cloud/aws/index.rst

---

 these pages appear to be incomplete

**Comment by seut** [comment]
As this issue does not give any hints what is meant by `incomplete`, I'll close it.

**Comment by amotl** [comment]
Hi @hammerhead, @hlcianfagna, and @proddata. Can you guess what "incomplete" might mean in this context. I am sure it might be easy to spot for the more initiated.

**Comment by hammerhead** [comment]
I looked into it previously, but also couldn't come to a conclusion as to what might have been perceived as being incomplete. Or what that section even looked like back in 2020, maybe it got addressed already along the way. From that perspective, I'd also consider it done until we get further feedback first-hand.
