### ISSUE TITLE
Can't install on Raspberry Pi4

### ISSUE THREAD

**Issue by PeterQuinn925** [crate/cratedb-guide#26]
###  Documentation feedback

 
- Page title: Run CrateDB on Ubuntu
- Page URL: https://crate.io/docs/crate/howtos/en/latest/deployment/linux/ubuntu.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/deployment/linux/ubuntu.rst

---

Doing some testing/learning/evaluation on a Raspberry Pi 4. I attempted 64 bit Ubuntu, but Crate did not appear to support the architecture. Now trying 32 bit 20.04 LTS 32 bit. Get the error message: **Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://cdn.crate.io/downloads/deb/stable focal InRelease' doesn't support architecture 'armhf'**

It would be nice to know beforehand what architectures are supported before installing a listed supported OS and find out it isn't on a some architectures. Better yet, instructions on how to get Crate installed on different architectures would be appreciated.

**Comment by seut** [comment]
Since CrateDB v5.5.1 we publish  Debian/Ubuntu ARM 64bit packages, see https://cdn.crate.io/downloads/debian/stable/pool/main/.
If you still experience issues, please re-open.
