### ISSUE TITLE
Documentation feedback on /docs/integrate/etl/mongodb.rst

### ISSUE THREAD

**Issue by amotl** [crate/cratedb-guide#76]
### Documentation feedback

 
- Page title: Import data from MongoDB
- Page URL: https://cratedb.com/docs/guide/integrate/etl/mongodb.html
- Source: https://github.com/crate/cratedb-guide/blob/main/docs/integrate/etl/mongodb.rst

---

The page still references the [MongoDB migration tool](https://github.com/crate/mongodb-cratedb-migration-tool). It should be using [CrateDB Toolkit](https://github.com/crate-workbench/cratedb-toolkit) now, and also tell how to install it, most likely using `pip install 'cratedb-toolkit[mongodb]'`.

The `migr8` command probably works as-is, but it may make sense to additionally present the new `ctk load table` interface of the [MongoDB I/O subsystem](https://github.com/crate-workbench/cratedb-toolkit/tree/main/cratedb_toolkit/io#mongodb), similar to the one for InfluxDB.

/cc @matkuliak

**Comment by amotl** [comment]
Both documents do not mention cr8 in this context yet, but [MongoDB to CrateDB - migr8 github project](https://crateio.atlassian.net/wiki/spaces/CE/pages/565543014/MongoDB+to+CrateDB+-+migr8+github+project) does.

**Comment by amotl** [comment]
The project now has a proper documentation, which will need to be taken into account accordingly, when improving the situation.

-- https://cratedb-toolkit.readthedocs.io/io/mongodb/

**Comment by matkuliak** [comment]
Would you mind if I picked this up @amotl ?
Or are you working on it already?

**Comment by amotl** [comment]
I am not working on this yet, and I appreciate any support. Thanks!
